# Generated by Django 4.2.5 on 2024-05-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_buy_property_terminated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcategory',
            options={'verbose_name_plural': 'Ad Categories'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
