# Generated by Django 4.2.5 on 2024-05-13 07:10

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_adcategory_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reachable_phone_number',
            field=models.CharField(default='', max_length=255, null=True, validators=[apps.core.validators.validate_phone_number]),
        ),
    ]
