# Generated by Django 4.2.5 on 2024-06-28 16:28

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_promoteadrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoteadrequest',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[apps.core.validators.validate_phone_number]),
        ),
        migrations.CreateModel(
            name='ContactCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30, validators=[apps.core.validators.validate_phone_number])),
                ('message', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contact', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_contact', to='property.property')),
            ],
            options={
                'verbose_name_plural': 'Contact Companies',
            },
        ),
    ]
