# Generated by Django 4.2.5 on 2024-07-04 06:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_promoteadrequest_phone_number_contactcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcategory',
            options={'verbose_name': 'Ad Category', 'verbose_name_plural': 'Ad Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactcompany',
            options={'verbose_name': 'Contact Company', 'verbose_name_plural': 'Contact Companies'},
        ),
        migrations.AlterModelOptions(
            name='favoriteproperty',
            options={'verbose_name': 'Favorite Property', 'verbose_name_plural': 'Favorite Properties'},
        ),
        migrations.AlterModelOptions(
            name='promoteadrequest',
            options={'verbose_name': 'Promote Ad Request', 'verbose_name_plural': 'Promote Ad Requests'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyfeature',
            options={'verbose_name': 'Property Feature', 'verbose_name_plural': 'Property Features'},
        ),
        migrations.AlterModelOptions(
            name='propertymedia',
            options={'verbose_name': 'Property Media', 'verbose_name_plural': 'Property Medias'},
        ),
        migrations.AlterModelOptions(
            name='propertystate',
            options={'verbose_name': 'Property State', 'verbose_name_plural': 'Property States'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'Property Type', 'verbose_name_plural': 'Property Types'},
        ),
        migrations.AlterField(
            model_name='adcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[apps.core.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='buy_or_rent',
            field=models.BooleanField(default=False, verbose_name='Buy or Rent'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='desired_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desired Price'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[apps.core.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='property_type',
            field=models.CharField(max_length=255, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='rooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='sell',
            field=models.BooleanField(default=False, verbose_name='Sell'),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='surface',
            field=models.PositiveIntegerField(default=0, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ad_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100, verbose_name='Ad Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=255, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='car_parking',
            field=models.PositiveIntegerField(default=1, verbose_name='Car Parking'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='property',
            name='entry_date',
            field=models.DateField(null=True, verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(default=20, verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ground_level',
            field=models.BooleanField(default=False, verbose_name='Ground Level'),
        ),
        migrations.AlterField(
            model_name='property',
            name='matterport_view_link',
            field=models.CharField(max_length=255, null=True, verbose_name='Matterport View Link'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name_of_lister',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of Lister'),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_balcony',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Balcony'),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='reachable_phone_number',
            field=models.CharField(default='', max_length=255, null=True, validators=[apps.core.validators.validate_phone_number], verbose_name='Reachable Phone Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Street Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='surface_build',
            field=models.PositiveIntegerField(default=0, verbose_name='Surface Build'),
        ),
        migrations.AlterField(
            model_name='property',
            name='terminated',
            field=models.BooleanField(default=False, verbose_name='Terminated'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_surface',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Surface'),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='media',
            field=models.FileField(upload_to='property_media', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
