# Generated by Django 4.2.5 on 2024-07-05 10:11

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_adcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcategory',
            options={'verbose_name_plural': 'Ad Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactcompany',
            options={'verbose_name_plural': 'Contact Companies'},
        ),
        migrations.AlterModelOptions(
            name='favoriteproperty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promoteadrequest',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyfeature',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='propertymedia',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='propertystate',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='adcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactcompany',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[apps.core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='buy_or_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='desired_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='phone_number',
            field=models.CharField(max_length=30, validators=[apps.core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='property_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promoteadrequest',
            name='surface',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='ad_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='car_parking',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='ground_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='matterport_view_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='name_of_lister',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_balcony',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='reachable_phone_number',
            field=models.CharField(default='', max_length=255, null=True, validators=[apps.core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='surface_build',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_surface',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='media',
            field=models.FileField(upload_to='property_media'),
        ),
        migrations.AlterField(
            model_name='propertystate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
