# Generated by Django 5.0.4 on 2024-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employeeprofile_user_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
