# Generated by Django 5.0.4 on 2024-04-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsecret',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
