# Generated by Django 5.0.4 on 2024-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_otpsecret_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsecret',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
