# Generated by Django 5.0.4 on 2024-04-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='num_of_referrals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
