# Generated by Django 4.2.5 on 2024-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agentprofile_normalprofile_remove_referral_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='license_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
