# Generated by Django 4.2.5 on 2024-05-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_agentprofile_license_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentProfile',
            new_name='CompanyProfile',
        ),
    ]
