# Generated by Django 4.2.5 on 2024-05-13 07:13

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_agentprofile_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True, validators=[apps.core.validators.validate_phone_number])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='static/profile_images/company_agents')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_agents', to='core.companyprofile')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
