# Generated by Django 4.2.5 on 2024-05-19 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_companyagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('days', models.CharField(max_length=255, null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_days', to='core.companyprofile')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
