# Generated by Django 4.2.5 on 2024-05-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_companyavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyavailability',
            name='days',
        ),
        migrations.AddField(
            model_name='companyavailability',
            name='last_day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyavailability',
            name='start_day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_day', to='core.companyprofile'),
        ),
    ]
