# Generated by Django 4.2.5 on 2024-05-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_companyavailability_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyavailability',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_days', to='core.companyprofile'),
        ),
    ]
