# Generated by Django 4.2.5 on 2024-07-04 06:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_companyavailability_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyagent',
            options={'verbose_name': 'Company agent', 'verbose_name_plural': 'Company agents'},
        ),
        migrations.AlterModelOptions(
            name='companyavailability',
            options={'verbose_name': 'Company availability', 'verbose_name_plural': 'Company availabilities'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company profile', 'verbose_name_plural': 'Company profiles'},
        ),
        migrations.AlterModelOptions(
            name='normalprofile',
            options={'verbose_name': 'Normal profile', 'verbose_name_plural': 'Normal profiles'},
        ),
        migrations.AlterField(
            model_name='companyagent',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='companyagent',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, validators=[apps.core.validators.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='companyagent',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images/company_agents', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='last_day',
            field=models.CharField(max_length=20, null=True, verbose_name='last day'),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='start_day',
            field=models.CharField(max_length=20, null=True, verbose_name='start day'),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_bg_images', verbose_name='background image'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=255, null=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='license_number',
            field=models.CharField(max_length=255, null=True, verbose_name='license number'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(max_length=255, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='normalprofile',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='normalprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_provider',
            field=models.BooleanField(default=False, verbose_name='google provider'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, validators=[apps.core.validators.validate_phone_number], verbose_name='phone number'),
        ),
        migrations.DeleteModel(
            name='OTPSecret',
        ),
    ]
