# Generated by Django 4.2.5 on 2024-07-05 10:11

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_companyagent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyagent',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='companyavailability',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='normalprofile',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='companyagent',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyagent',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, validators=[apps.core.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='companyagent',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images/company_agents'),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='last_day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='start_day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyavailability',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_bg_images'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='license_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='normalprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='normalprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, validators=[apps.core.validators.validate_phone_number]),
        ),
    ]
